model_list:
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: "anthropic/claude-3-5-sonnet-20240620"
      api_key: "ANTHROPIC_API_KEY"
    model_info:
      supports_vision: True
  - model_name: gpt-4o
    litellm_params:
      model: "openai/gpt-4o"
      api_key: "OPENAI_API_KEY"
    model_info:
      supports_vision: True
  - model_name: "llama3.2"             
    litellm_params:
      model: "ollama_chat/llama3.2"
