# Make a copy of the file and rename it to `secrets.toml`.

IS_AZURE = false (true for Azure else false)
MODEL_BASE_URL = "Your server url"
MODEL_API_KEY = "Your model api key" (empty for local model)
MODEL_NAMES = "Your available model names as array Eg: ['gpt-4', 'gpt-4o']"
VISION_MODELS = "Above models with vision capability as array Eg: ['gpt-4o']"
TAVILY_API_KEY = "Your Tavily API Key"
LANGFUSE_SECRET_KEY = "Your Langfuse Secret Key"
LANGFUSE_PUBLIC_KEY = "Your Langfuse Public Key"