# Make a copy of the file and rename it to `secrets.toml`.

REPLICATE_API_TOKEN = "Your Replicate API Token"
TAVILY_API_KEY = "Your Tavily API Key"
LANGFUSE_SECRET_KEY = "Your Langfuse Secret Key"
LANGFUSE_PUBLIC_KEY = "Your Langfuse Public Key"