# Make a copy of the file and rename it to `secrets.toml`.

MODEL_PROVIDER = "AZURE"
MODEL_BASE_URL = "Your server url"
MODEL_NAMES = "Your model name"
IS_VISION_MODEL = true (true for vision model else false)
MODEL_API_KEY = "Your model api key" (empty for local model)
TAVILY_API_KEY = "Your Tavily API Key"
LANGFUSE_SECRET_KEY = "Your Langfuse Secret Key"
LANGFUSE_PUBLIC_KEY = "Your Langfuse Public Key"