# Make a copy of the file and rename it to `secrets.toml`.

MODEL_PROVIDER = "openai or gemini"
MODEL_API_TOKEN = "Your Model API Token"
TAVILY_API_KEY = "Your Tavily API Key"
LANGFUSE_SECRET_KEY = "Your Langfuse Secret Key"
LANGFUSE_PUBLIC_KEY = "Your Langfuse Public Key"